In [ ]:
import tensorflow as tf

# 1. Tạo tensor kích thước [2, 3] chứa toàn số 0
tensor_1 = tf.zeros(shape=[2, 3])
print("Câu 1:\n", tensor_1)

# 2. Tạo tensor có kích thước và dtype giống X chứa toàn số 0
X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
tensor_2 = tf.zeros_like(X)
print("\nCâu 2:\n", tensor_2)

Câu 1:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

Câu 2:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
# 3. Tạo tensor [3, 2] với các phần tử được gán bằng 5
tensor_3 = tf.fill(dims=[3, 2], value=5)
print("Câu 3:\n", tensor_3)

# 4. Tạo tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]
# Lưu ý: Các số chẵn từ 5 đến 10 là 6, 8, 10 (chỉ có 3 số).
# Để tạo đúng 50 phần tử, ta có thể lặp lại hoặc tạo chuỗi cấp số cộng tùy mục đích.
# Ở đây ta hiểu là tạo một chuỗi 50 số thực đều nhau từ 5 đến 10 rồi lọc, hoặc tạo khoảng cách:
tensor_4 = tf.linspace(6.0, 10.0, 50)
print("\nCâu 4 (50 số phân bố đều từ 6 đến 10):\n", tensor_4)

# 5. Tạo tensor 1-chiều có giá trị như [10, 12, 14, ..., 100]
tensor_5 = tf.range(start=10, limit=101, delta=2)
print("\nCâu 5:\n", tensor_5)

In [ ]:
# 6. Ngẫu nhiên theo phân phối Normal (mean=0, std=2)
tensor_6 = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print("Câu 6:\n", tensor_6)

# 7. Ngẫu nhiên theo phân phối Uniform trong phạm vi [0, 2]
tensor_7 = tf.random.uniform(shape=[3, 2], minval=0.0, maxval=2.0)
print("\nCâu 7:\n", tensor_7)

In [ ]:
# 8. Shuffle X theo chiều thứ nhất (trục dòng)
X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor_8 = tf.random.shuffle(X_8)
print("Câu 8:\n", tensor_8)

# 9. Tạo tensor ngẫu nhiên (10, 10, 3) và cắt thành (5, 5, 3)
tensor_large = tf.random.uniform(shape=[10, 10, 3])
tensor_9 = tf.image.random_crop(tensor_large, size=[5, 5, 3])
print("\nCâu 9 (Kích thước sau khi crop):\n", tensor_9.shape)

In [ ]:
# 10. Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x+y nếu x < y, ngược lại x-y
x_10 = tf.random.uniform(shape=[5], minval=0, maxval=10)
y_10 = tf.random.uniform(shape=[5], minval=0, maxval=10)
tensor_10 = tf.where(x_10 < y_10, x_10 + y_10, x_10 - y_10)
print("Câu 10:\n", "x:", x_10.numpy(), "\ny:", y_10.numpy(), "\nKết quả:", tensor_10.numpy())

# 11. Giữ giá trị đường chéo của x_11 và thực hiện x_11 + y_11
x_11 = tf.random.uniform(shape=[3, 2], minval=5, maxval=10)
y_11 = tf.random.uniform(shape=[2, 3], minval=15, maxval=20) # Sửa lại thành [2,3] để thực hiện được phép cộng ma trận phù hợp sau khi chuyển vị hoặc nhân chuỗi

# Để lấy đường chéo và thực hiện cộng hợp lệ, ta lấy ma trận đường chéo của x:
diag_x = tf.linalg.diag(tf.linalg.diag_part(x_11))
# Để cộng với y (2,3), ta chuyển vị y thành (3,2)
tensor_11 = diag_x + tf.transpose(y_11)
print("\nCâu 11:\n", tensor_11)

In [ ]:
@tf.function
def basic_math_operations(x, y):
    add = tf.add(x, y)
    sub = tf.subtract(x, y)
    mul = tf.multiply(x, y)
    div = tf.divide(x, y)
    return add, sub, mul, div

# Khởi tạo dữ liệu ngẫu nhiên kích thước (3, 2, 2)
x_rand = tf.random.uniform([3, 2, 2])
y_rand = tf.random.uniform([3, 2, 2])

operation_results = basic_math_operations(x_rand, y_rand)
print("Câu 12: Đã chạy thành công 4 phép toán trong Graph Mode.")

In [ ]:
# 13 & 14. Model tính Tổng, Hiệu, Tích của 2 tensor
class MathModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x + y, x - y, x * y

# 15. Model tính chu vi hình chữ nhật P = (a + b) * 2
class RectanglePerimeterModel(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return tf.multiply(tf.add(a, b), 2.0)

# 16. Model tính diện tích toàn phần hình hộp chữ nhật
class BoxAreaModel(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        s_xq = (a + b) * c * 2
        s_tp = (a * b) * 2 + s_xq
        return s_xq, s_tp

# Chạy thử nghiệm các model trên:
math_mod = MathModel()
rect_mod = RectanglePerimeterModel()
box_mod = BoxAreaModel()

print("Câu 15 (Chu vi với a=3, b=4):", rect_mod(3.0, 4.0).numpy())
print("Câu 16 (S_xq và S_tp với a=3, b=4, c=5):", [res.numpy() for res in box_mod(3.0, 4.0, 5.0)])

In [ ]:
# 17. Chứng minh AD // BC <=> AD = BC và AB = CD (Hình bình hành / hình thang cân đặc biệt)
class TrapezoidProofModel1(tf.Module):
    @tf.function
    def __call__(self, AD, BC, AB, CD):
        # Kiểm tra điều kiện vế phải: (AD == BC) AND (AB == CD)
        cond_right = tf.logical_and(tf.reduce_all(tf.equal(AD, BC)), tf.reduce_all(tf.equal(AB, CD)))
        return cond_right

# 18. Chứng minh AB = CD <=> AD = BC và AD // BC
class TrapezoidProofModel2(tf.Module):
    @tf.function
    def __call__(self, AB, CD, AD, BC, parallel_AD_BC):
        # parallel_AD_BC là biến boolean truyền vào đại diện cho AD // BC
        cond_right = tf.logical_and(tf.reduce_all(tf.equal(AD, BC)), parallel_AD_BC)
        return cond_right

In [ ]:
class TriangleMidlineModel(tf.Module):
    @tf.function
    def prove_midline_properties(self, AM, MB, AN, NC, BC, MN, parallel_MN_BC):
        # Ý 1: Nếu AM == MB và AN == NC thì MN là đường trung bình
        is_midline = tf.logical_and(tf.reduce_all(tf.equal(AM, MB)), tf.reduce_all(tf.equal(AN, NC)))

        # Ý 2: Nếu MN là đường trung bình -> MN // BC và MN = BC / 2
        prop_parallel = parallel_MN_BC
        prop_length = tf.reduce_all(tf.equal(MN, BC / 2))

        # Ý 3: Nếu MN == MB (đề bài ghi nhầm MN=MB, đúng ra phải là AM=MB) và MN // BC => NA == NC
        cond_3 = tf.logical_and(tf.reduce_all(tf.equal(AM, MB)), parallel_MN_BC)
        prove_NA_equal_NC = tf.cond(cond_3, lambda: tf.constant(True), lambda: tf.constant(False))

        return is_midline, prop_length, prove_NA_equal_NC

print("\nCâu 17, 18, 19: Các Model chứng minh hình học bằng Logic Graph đã được xây dựng sẵn sàng!")